# Generated by Django 6.0.9 on 2026-10-06 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_purchase_retention_days', models.PositiveIntegerField(default=30, verbose_name='durée de conservation des achats reçus (jours)')),
            ],
            options={
                'verbose_name': 'paramètre technique',
                'verbose_name_plural': 'paramètres techniques',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='planned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='date prévue'),
        ),
    ]
